export const CHANGE_PARTNERINFO_INPUT = "CHANGE_PARTNERINFO_INPUT";
export const PARTNER_INFO_SUBMIT = "PARTNER_INFO_SUBMIT";
export const GET_TAX_TYPE = "GET_TAX_TYPE";
export const GET_PARTNER_TYPE = "GET_PARTNER_TYPE";
export const GET_BUSINESS_TYPE = "GET_BUSINESS_TYPE";
export const EMPTY_PARTNER_INFO = "EMPTY_PARTNER_INFO";
export const EDIT_PARTNER_INFO = "EDIT_PARTNER_INFO";