export const BASIC_INFO_INPUT = "BASIC_INFO_INPUT";
export const CHANGE_ADMININFO_INPUT = "CHANGE_ADMININFO_INPUT";
export const GET_SUPPLIER_NAME = "GET_SUPPLIER_NAME";
export const GET_COUNTRY_NAME = "GET_COUNTRY_NAME";
export const GET_ASSET_LOCATION = "GET_ASSET_LOCATION";
export const SUBMIT_ADMIN_INFO = "SUBMIT_ADMIN_INFO";
export const SUBMITTING = "SUBMITTING";
/**********************Account Information********************* */
export const CHANGE_ACCOUNT_INFO_INPUT = "CHANGE_ACCOUNT_INFO_INPUT";
export const SUBMIT_ACCOUNT_INFO = "SUBMIT_ACCOUNT_INFO";
export const CHANGE_ADMIN_LIST_FILTER_INPUT = "CHANGE_ADMIN_LIST_FILTER_INPUT";
export const GET_ADMIN_INFO_LIST = "GET_ADMIN_INFO_LIST";
export const EMPTY_ADMIN = "EMPTY_ADMIN";
export const EDIT_ADMIN_INFO = "EDIT_ADMIN_INFO";
export const UPDATE_ADMIN_INFO = "UPDATE_ADMIN_INFO";
