export const BASIC_INFO_INPUT = "BASIC_INFO_INPUT";
export const CHANGE_ADMININFO_INPUT = "CHANGE_ADMININFO_INPUT";
export const GET_SUPPLIER_NAME = "GET_SUPPLIER_NAME";
export const GET_COUNTRY_NAME = "GET_COUNTRY_NAME";
export const GET_ASSET_LOCATION = "GET_ASSET_LOCATION";
export const SUBMIT_ADMIN_INFO = "SUBMIT_ADMIN_INFO";