export const CHANGE_PO_APPROVAL_FILTER_INPUT = "CHANGE_PO_APPROVAL_FILTER_INPUT";
export const GET_SHIP_NAME = "GET_SHIP_NAME";
export const GET_SBU_NAME = "GET_SBU_NAME";
export const GET_BRANCH_NAME = "GET_BRANCH_NAME";
export const GET_PO_APPROVAL_LIST = "GET_PO_APPROVAL_LIST";
export const GET_REFERENCE_TYPE = "GET_REFERENCE_TYPE";


