/*************** CERTIFICATE ******************/
export const CHANGE_CERTIFICATE_MASTER_INPUT = "CHANGE_CERTIFICATE_MASTER_INPUT";
export const CERTIFICATE_MASTER_SUBMIT = "CERTIFICATE_MASTER_SUBMIT";
export const GET_CERTIFICATE_MASTER_LIST = "GET_CERTIFICATE_MASTER_LIST";
export const CREATE_CERTIFICATE_MASTER_LIST = "CREATE_CERTIFICATE_MASTER_LIST";

/*************** CERTIFICATE ******************/