export const CHANGE_ITEM_INPUT = "CHANGE_ITEM_INPUT";
export const MULTIPLE_ITEM_ADD_INPUT = "MULTIPLE_ITEM_ADD_INPUT";
export const DELETE_MULTIPLE_ITEM = "DELETE_MULTIPLE_ITEM";
export const GET_ITEM_CATEGORY = "GET_ITEM_CATEGORY";