export const CHANGE_BANKINFO_INPUT = "CHANGE_BANKINFO_INPUT";
export const SUBMIT_BANK_INFO_MULTIPLE = "SUBMIT_BANK_INFO_MULTIPLE";
export const EMPTY_ADD_MULTIPLE_FIELDS = "EMPTY_ADD_MULTIPLE_FIELDS";
export const DELETE_PARTNER_BANK_MULTIPLE = "DELETE_PARTNER_BANK_MULTIPLE";
export const GET_BANK_NAME = "GET_BANK_NAME";
export const EMPTY_BANK_INFO = "EMPTY_BANK_INFO";
export const EDIT_BANK_INFO = "EDIT_BANK_INFO";   