export const CHANGE_BANKINFO_INPUT = "CHANGE_BANKINFO_INPUT";
export const SUBMIT_BANK_INFO_MULTIPLE = "SUBMIT_BANK_INFO_MULTIPLE";
export const DELETE_PARTNER_BANK_MULTIPLE = "DELETE_PARTNER_BANK_MULTIPLE";