export const GET_DEPARTMENT_LIST = "GET_DEPARTMENT_LIST";
export const SUPPLIER_CS_INPUT = "SUPPLIER_CS_INPUT";
export const SEARCH_SUPPLIER = "SEARCH_SUPPLIER";
export const SUPPLIER_LIST = "SUPPLIER_LIST";
export const GET_SUPPLIER_DETAILS = "GET_SUPPLIER_DETAILS";
export const GET_SUPPLIER_ADDRESS = "GET_SUPPLIER_ADDRESS";
export const SEARCH_RFQ = "SEARCH_RFQ";
export const QUOTATION_RFQ_LIST = "QUOTATION_RFQ_LIST";