/*************** CERTIFICATE ******************/
export const CERTIFICATE_LIST_HOME = "CERTIFICATE_LIST_HOME";
export const CERTIFICATE_LIST_DASHBOARD = "CERTIFICATE_LIST_DASHBOARD";
export const CERTIFICATE_LIST_LOADING = "CERTIFICATE_LIST_LOADING";
export const CERTIFICATE_DETAIL = "CERTIFICATE_DETAIL";

export const CHANGE_CERTIFICATE_INPUT = "CHANGE_CERTIFICATE_INPUT";
export const CHANGE_CERTIFICATE_INPUT_UPDATE = "CHANGE_CERTIFICATE_INPUT_UPDATE";
export const EMPTY_CERTIFICATE_MESSAGE = "EMPTY_CERTIFICATE_MESSAGE";
export const LOADING = "UPDATE_LOADING";
export const EDITING = "EDITING";
export const DELETING = "DELETING";
export const CREATE_CERTIFICATE = "CREATE_CERTIFICATE";
export const EDIT_CERTIFICATE_INFO = "EDIT_CERTIFICATE";
export const UPDATE_CERTIFICATE = "UPDATE_CERTIFICATE";
export const DELETE_CERTIFICATE = "DELETE_CERTIFICATE";
/*************** CERTIFICATE ******************/