export const GET_USER_ROLE_LIST="GET_USER_ROLE_LIST";
export const USER_ROLE_CHECKED="USER_ROLE_CHECKED";
export const USER_ROLE_ALL_CHECKED="USER_ROLE_ALL_CHECKED";
export const USER_ROLE_CHECKED_GROUP="USER_ROLE_CHECKED_GROUP";
export const GET_USER_ROLE_POST="GET_USER_ROLE_POST";
export const USER_ROLE_HANDLE_CHANGE="USER_ROLE_HANDLE_CHANGE";