export const GET_USER_ROLE_LIST="GET_USER_ROLE_LIST";
export const USER_ROLE_CHECKED="USER_ROLE_CHECKED";
export const USER_ROLE_ALL_CHECKED="USER_ROLE_ALL_CHECKED";
export const USER_ROLE_CHECKED_GROUP="USER_ROLE_CHECKED_GROUP";