export const GET_LAYTIME_LIST = "GET_LAYTIME_LIST";
export const CHANGE_LAYTIME_HEADER_INPUT = "CHANGE_LAYTIME_HEADER_INPUT";
export const CHANGE_LAYTIME_DETAIL_INPUT = "CHANGE_LAYTIME_DETAIL_INPUT";
