export const GET_LAYTIME_LIST = "GET_LAYTIME_LIST";
export const CHANGE_LAYTIME_HEADER_INPUT = "CHANGE_LAYTIME_HEADER_INPUT";
export const CHANGE_LAYTIME_DETAIL_INPUT = "CHANGE_LAYTIME_DETAIL_INPUT";
export const GET_CURRENCY_DATA = "GET_CURRENCY_DATA";
//get header input from api
export const GET_HEADER_INPUT_FROM_API = "GET_HEADER_INPUT_FROM_API";
//GET VOYAGE ID
export const GET_VOYAGE_ID = "GET_VOYAGE_ID";
