export const CHANGE_QUOTATION_FILTER_INPUT = "CHANGE_QUOTATION_FILTER_INPUT";
export const GET_SUPPLIER_NAME = "GET_SUPPLIER_NAME";
export const GET_CURRENCY_TYPE = "GET_CURRENCY_TYPE";
export const GET_QUOTATION_DETAILS = "GET_QUOTATION_DETAILS";
export const SUBMIT_QUOTATION = "GET_QUOTATION_DETAILS";