// export const GET_ADDRESS_ACTION_SUBMIT = "GET_ADDRESS_ACTION_SUBMIT";
export const CHANGE_PARTNER_ADDRESS_INPUT = "CHANGE_PARTNER_ADDRESS_INPUT";
export const SUBMIT_PARTNER_ADDRESS = "SUBMIT_PARTNER_ADDRESS";
export const SUBMIT_PARTNER_ADDRESS_MULTIPLE = "SUBMIT_PARTNER_ADDRESS_MULTIPLE";
export const DELETE_PARTNER_ADDRESS_MULTIPLE = "DELETE_PARTNER_ADDRESS_MULTIPLE";
export const GET_COUNTRY_NAME = "GET_COUNTRY_NAME";
export const EMPTY_ADDRESS_INFO = "EMPTY_ADDRESS_INFO";