export const CERTIFICATE_CATEGORY_CREATE = "CERTIFICATE_CATEGORY_CREATE";
export const CERTIFICATE_CATEGORY_STORE = "CERTIFICATE_CATEGORY_STORE";
export const GET_CERTIFICATE_CATEGORY_LIST = "GET_CERTIFICATE_CATEGORY_LIST";