export const CERTIFICATE_CATEGORY_CREATE = "CERTIFICATE_CATEGORY_CREATE";
export const CERTIFICATE_CATEGORY_STORE = "CERTIFICATE_CATEGORY_STORE";
export const GET_CERTIFICATE_CATEGORY_LIST = "GET_CERTIFICATE_CATEGORY_LIST";
export const SET_CERTIFICATE_CATEGORY_EDIT_DATA = "SET_CERTIFICATE_CATEGORY_EDIT_DATA";
export const EDIT_CERTIFICATE_CATEGORY = "EDIT_CERTIFICATE_CATEGORY";
export const GET_CERTIFICATE_PARENT_CATEGORY_LIST = "GET_CERTIFICATE_PARENT_CATEGORY_LIST";
export const GET_CERTIFICATE_CHILD_CATEGORY_LIST = "GET_CERTIFICATE_CHILD_CATEGORY_LIST";