// Vessel booking entry
export const VESSEL_BOOKING_INPUT_CHANGE = "VESSEL_BOOKING_INPUT_CHANGE";
export const GET_BROKER_LIST = "GET_BROKER_LIST";
//submit 

export const VESSEL_BOOKING_SUBMIT = "VESSEL_BOOKING_SUBMIT";
export const VESSEL_BOOKING_SUBMITTING = "VESSEL_BOOKING_SUBMITTING";

// get vessel bookig list 
export const GET_VESSEL_BOOKING_LIST = "GET_VESSEL_BOOKING_LIST";