export const CHANGE_PARTNER_OTHERINFO_INPUT = "CHANGE_PARTNER_OTHERINFO_INPUT";
export const PARTNER_OTHERINFO_SUBMIT = "PARTNER_OTHERINFO_SUBMIT";
export const GET_PORT_NAME = "GET_PORT_NAME";
export const GET_PROVIDER_NAME = "GET_PROVIDER_NAME";
export const EMPTY_OTHERS_INFO = "EMPTY_OTHERS_INFO";
export const EDIT_OTHERS_INFO = "EDIT_OTHERS_INFO";
export const DELETED_PORTS = "DELETED_PORTS";
export const DELETED_PROVIDER = "DELETED_PROVIDER";