export const GET_SUPPLIER_LIST = "GET_SUPPLIER_LIST";
export const DELETE_SUPPLIER_LIST = "DELETE_SUPPLIER_LIST";
export const SUPPLIER_DETAILS = "SUPPLIER_DETAILS";
export const CHANGE_SUPPLIER_FILTER_INPUT = "CHANGE_SUPPLIER_FILTER_INPUT";
export const GET_SUPPLIER_TYPE_NAME = "GET_SUPPLIER_TYPE_NAME";