export const CHANGE_CERTIFICATE_TYPE_INPUT = "CHANGE_CERTIFICATE_TYPE_INPUT";
export const GET_CERTIFICATE_TYPE_LIST = "GET_CERTIFICATE_TYPE_LIST";
export const CREATE_CERTIFICATE_TYPE = "CREATE_CERTIFICATE_TYPE";
export const EDIT_CERTIFICATE_TYPE_LIST = "EDIT_CERTIFICATE_TYPE_LIST";